# Numpy exercise

{badge}`python3,badge-success` {badge}`data science,badge-secondary` {badge}`numpy,badge-warning` 

Numpy is 

- Dimensions
- Slicing

{cite}`285005`

In [1]:
import numpy as np

Initializing arrays - pass list

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = np.array([np.arange(4), np.arange(4,8),np.arange(8,12)])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
c = b[:,np.newaxis]
c

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [37]:
c.shape

(3, 1, 4)

In [46]:
c[2,:,1]

array([9])

In [43]:
c[2]

array([[ 8,  9, 10, 11]])

In [28]:
d = b[np.newaxis,:]
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

(3, 1, 4)

In [36]:
d.shape

(1, 3, 4)

In [2]:
x = np.array([[[ 0,  1,  2,  3],
...                [ 4,  5,  6,  7],
...                [ 8,  9, 10, 11]],
...
...               [[12, 13, 14, 15],
...                [16, 17, 18, 19],
...                [20, 21, 22, 23]]])

In [33]:
x.shape

(2, 3, 4)

In [35]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Normalize x such that each of its rows, within each sheet, will sum to a value of 1. Make use of the sequential function np.sum, which should be called only once, and broadcast-division.



In [45]:
xsum = np.sum(x, axis=(2))
xsum

array([[ 6, 22, 38],
       [54, 70, 86]])

In [46]:
xsum.shape


(2, 3)

In [49]:
x/xsum[...,np.newaxis]

array([[[0.        , 0.16666667, 0.33333333, 0.5       ],
        [0.18181818, 0.22727273, 0.27272727, 0.31818182],
        [0.21052632, 0.23684211, 0.26315789, 0.28947368]],

       [[0.22222222, 0.24074074, 0.25925926, 0.27777778],
        [0.22857143, 0.24285714, 0.25714286, 0.27142857],
        [0.23255814, 0.24418605, 0.25581395, 0.26744186]]])

In [87]:
images = np.random.rand(500, 48, 48, 3)
imgsmall = np.random.rand(3, 4, 4, 3)
imgsmall[0][0]
#stores as a single array

array([[0.50838982, 0.75219019, 0.81813862],
       [0.5027365 , 0.7130246 , 0.06910815],
       [0.38349565, 0.93492598, 0.92332256],
       [0.42988345, 0.97348542, 0.48313158]])

Using the sequential function np.max and broadcasting, normalize images such that the largest value within each color-channel of each image is 1.

In [81]:
imgsmall[0][0][1]

array([0.61702995, 0.40418564, 0.2634068 ])

In [89]:
np.max(imgsmall, axis=(1,2))

array([[0.89079141, 0.97348542, 0.92332256],
       [0.98598891, 0.89502278, 0.9847218 ],
       [0.74632897, 0.98611314, 0.96694708]])

## Bibliography

```{bibliography} ../_bibliography/references.bib
:style: plain
:filter: docname in docnames
```